all:
  vars:
    ansible_ssh_user: svcrhelansibleacc
    openshift_image_tag: "v3.9.14"
    openshift_pkg_version: "-3.9.14"
    #ansible_ssh_user: extary
    #ansible_become_pass: !vault |
      # ADD VAULT HERE
    # Need to use --become from commandline to playbooks work correctly
    # You SHOULD NOT EVER USE ansible_become on hosts, because this overrides EVERY PLACES!
    #ansible_become: false
    debug_level: 2
  children:
    bastion:
      hosts:
        bastion
    OSEv3:
      # Create an OSEv3 group that contains the masters and nodes groups
      children:
        masters:
          hosts:
            host1:
            host2:
        etcd:
          hosts:
            host3:
        nodes:
          hosts:
            node1:
              # Labels to identify nodes and point to configuration to
              openshift_node_labels:
                role: master
                environment: prod
                node-role.kubernetes.io/master: true
            node2:
              openshift_node_labels:
                role: master
                environment: prod
                node-role.kubernetes.io/master: true
            node3:
              openshift_node_labels:
                role: master
                environment: prod
                node-role.kubernetes.io/master: true

      # Set variables common for all OSEv3 hosts
      vars:
        openshift_release: v3.9.14
        # Prereq checks we want to skip
        openshift_disable_check: docker_image_availability
        # Specify deployment type. Don't change
        openshift_deployment_type: openshift-enterprise
        # Temporary admin until AD authentication
        openshift_master_htpasswd_users:
          localadmin: 'yourpassword'
        # Upgrade specifics:
        openshift_rolling_restart_mode: system

        # GlusterFS Configuration
        openshift_storage_glusterfs_namespace: glusterfs
        openshift_storage_glusterfs_storageclass_default: True
        openshift_storage_glusterfs_storageclass: True
        openshift_storage_glusterfs_block_deploy: True
        openshift_storage_glusterfs_block_storageclass: True
        openshift_master_dynamic_provisioning_enabled: True

        # AD definitions for user identification
        openshift_master_identity_providers:
          - name: OpenShift local users
            login: true
            challenge: true
            kind: HTPasswdPasswordIdentityProvider
            filename: /etc/origin/master/htpasswd

        # Native high availability cluster method with optional load balancer.
        # If no lb group is defined, the installer assumes that a load balancer
        # has been preconfigured. For installation the value of
        # openshift_master_cluster_hostname must resolve to the load balancer
        # or to one or all of the masters defined in the inventory if no load
        # balancer is present.

        openshift_master_cluster_method: native
        openshift_master_cluster_hostname: internal.name
        openshift_master_cluster_public_hostname: external.name
        # default subdomain to use for exposed routes
        openshift_master_default_subdomain: apps.local
        # Kubernetes needs following value in ini-format
        osm_default_node_selector: "role=compute,environment=prod"
        # OpenShift Service network
        openshift_portal_net: 172.31.0.0/16
        # OpenShift pod network
        osm_cluster_network_cidr: 10.132.0.0/14
        # Manage the OpenShift Router (optional)
        openshift_hosted_manage_router: true
        openshift_hosted_router_replicas: 3
        # openshift_hosted_router_certificate:
        #   certfile: /path/to/router.crt
        #   keyfile: /path/to/router.key
        #   cafile: /path/to/router-ca.crt
        # openshift_hosted_routers:
        #   - name: router1
        #     certificate:
        #       certfile: /path/to/certificate/abc.crt
        #       keyfile: /path/to/certificate/abc.key
        #       cafile: /path/to/certificate/ca.crt
        #     replicas: 1
        #     serviceaccount: router
        #     namespace: default
        #     stats_port: 1936
        #     edits: []
        #     images: 'openshift3/ose-${component}:${version}'
        #     selector: 'type=router1'
        #     ports:
        #       - 80:80
        #       - 443:443

        openshift_hosted_etc_storage_kind: nfs
        openshift_hosted_etc_storage_access_modes:
          - ReadWritOnce
        # Storage host address
        openshift_hosted_etcd_storage_host: storage.local
        # nfs_directory must conform to DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character
        openshift_hosted_etcd_storage_nfs_directory: /vol/nfsOpenShift
        # Registry storage name
        openshift_hosted_etcd_storage_volume_name: hosted-etcd
        # Storage size
        openshift_hosted_etcd_storage_volume_size: 1Gi
        openshift_hosted_etcd_storage_labels:
          storage: etcd

        # Metrics installation configuration
        # To install or not to install {true|false}
        openshift_metrics_install_metrics: True
        openshift_metrics_storage_kind: dynamic
        openshift_metrics_cassandra_storage_type: dynamic
        openshift_metrics_cassandra_pvc_size: 50Gi
        # Selected nodes for metrics services
        openshift_metrics_cassandra_nodeselector:
          role: infra
          environment: prod
        openshift_metrics_hawkular_nodeselector:
          role: infra
          environment: prod
        openshift_metrics_heapster_nodeselector:
          role: infra
          environment: prod
        # Override metricsPublicURL in the master config for cluster metrics
        openshift_metrics_hawkular_hostname: metrics.apps.local
        # Project name in OpenShift
        openshift_metrics_project: openshift-infra

        #Logging installation configuration
        # To install or not to install {true|false}
        openshift_logging_install_logging: True
        openshift_logging_es_pvc_size: 25Gi
        openshift_logging_storage_kind: dynamic
        openshift_logging_es_cluster_size: 3
        openshift_logging_es_nodeselector:
          role: infra
          environment: prod
        openshift_logging_kibana_nodeselector:
          role: infra
          environment: prod
        openshift_logging_curator_nodeselector:
          role: infra
          environment: prod
        ## openshift_logging_storage_kind: dynamic
        ## Configure loggingPublicURL in the master config for aggregate logging
        openshift_logging_kibana_hostname: logging.apps.local
        openshift_logging_namespace: logging

        # To install or not to install {true|false}
        openshift_hosted_prometheus_deploy: True
        openshift_prometheus_state: present
        openshift_prometheus_image_version: v3.9
        openshift_prometheus_node_exporter_image_version: v3.9
        openshift_prometheus_proxy_image_version: v3.9
        openshift_prometheus_alertbuffer_image_version: v3.9
        openshift_prometheus_alertmanager_image_version: v3.9
        openshift_prometheus_namespace: openshift-metrics
        openshift_prometheus_storage_kind: glusterfs
        openshift_prometheus_storage_class: glusterfs-storage
        openshift_prometheus_storage_type: pvc
        openshift_prometheus_storage_volume_name: prometheus
        openshift_prometheus_storage_volume_size: 10Gi
        openshift_prometheus_alertmanager_storage_kind: glusterfs
        openshift_prometheus_alertmanager_storage_class: glusterfs-storage
        openshift_prometheus_alertmanager_storage_type: pvc
        openshift_prometheus_alertmanager_volume_name: prometheus-alertmanager
        openshift_prometheus_alertmanager_volume_size: 10Gi
        openshift_prometheus_alertbuffer_storage_kind: glusterfs
        openshift_prometheus_alertbuffer_storage_class: glusterfs-storage
        openshift_prometheus_alertbuffer_storage_type: pvc
        openshift_prometheus_alertbuffer_volume_name: prometheus-alertbuffer
        openshift_prometheus_alertbuffer_volume_size: 10Gi
        ## Nodes to for Prometheus
        openshift_prometheus_node_selector:
          role: infra
          environment: prod

        # This is used to configure Grafana metrics visualizer
        # To install or not {true | false}
        # There seems not to be any kind of toggle other than state to control the installation
        openshift_grafana_state: present
        openshift_grafana_namespace: openshift-grafana
        openshift_grafana_timeout: 300
        openshift_grafana_prometheus_namespace: openshift-metrics
        openshift_grafana_prometheus_serviceaccount: prometheus
        openshift_grafana_serviceaccount_name: grafana
        openshift_grafana_datasource_name: prometheus
        openshift_grafana_node_exporter: true
        openshift_grafana_graph_granularity: 2m
        openshift_grafana_node_selector:
          role: infra
          environment: prod
        # Collection of ready made dashboard to use
        openshift_grafana_dashboards:
          - openshift-cluster-monitoring.json
          - node-exporter-full-dashboard.json
        openshift_grafana_hostname: grafana.apps.local
        openshift_grafana_service_name: grafana
        openshift_grafana_service_port: 443
        openshift_grafana_service_targetport: 8443
        openshift_grafana_container_port: 3000
        # PVC for Grafana
        openshift_grafana_storage_type: pvc
        openshift_grafana_pvc_name: grafana
        openshift_grafana_sc_name: glusterfs-storage

        # OCP Network plugin for SDN
        os_sdn_network_plugin_name: redhat/openshift-ovs-networkpolicy

        # Configure custom ca certificate
        # CA certificate will not be replaced with existing clusters.
        # This option may only be specified when creating a new cluster or
        # when redeploying cluster certificates with the redeploy-certificates
        # playbook.
        openshift_master_ca_certificate:
          certfile: /etc/opt/ocp/ca/ca.crt
          keyfile: /etc/opt/ocp/ca/ca.key
        openshift_clock_enabled: true
        # Enable API service auditing
        openshift_master_audit_config:
          enabled: true
          auditFilePath: /var/log/openpaas-oscp-audit/openpaas-oscp-audit.log
          # Max. file size, retention days and files
          maximumFileSizeMegabytes: 500
          maximumRetainedFiles: 5
          maximumFileRetentionDays: 14
        # Provide local certificate paths which will be deployed to masters
        openshift_master_named_certificates:
          - certfile: /etc/opt/ocp/certs/public-api.crt
            keyfile: /etc/opt/ocp/certs/public-api.key
            names:
              - external.host
        template_service_broker_selector:
          role: infra
          environment: prod
        # Router selector (optional)
        # Router will only be created if nodes matching this label are present.
        openshift_hosted_router_selector: "role=infra,environment=prod"
        # Registry selector (optional)
        # Registry will only be created if nodes matching this label are present.
        openshift_hosted_registry_selector: "role=infra,environment=prod"
        # Configure master API and console ports.
        openshift_master_api_port: 443
        openshift_master_console_port: 443
        openshift_management_install_management: True
        openshift_management_install_beta: True
        openshift_management_app_template: cfme-template
        openshift_management_project: ocp-management
        # openshift_management_project_description:
        openshift_management_username: admin
        openshift_management_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          123123123
          123123123
        openshift_management_storage_class: preconfigured
